package com.curtisnewbie.module.outbox.dao;

import com.curtisnewbie.module.outbox.dao.ConsumedMessageEntity;

import java.util.List;

/**
 * Mapper for consumed_message
 *
 * @author yongjie.zhuang
 */
public interface ConsumedMessageMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table consumed_message
     *
     * @mbg.generated Mon Aug 30 19:52:12 CST 2021
     */
    int deleteByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table consumed_message
     *
     * @mbg.generated Mon Aug 30 19:52:12 CST 2021
     */
    int insert(ConsumedMessageEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table consumed_message
     *
     * @mbg.generated Mon Aug 30 19:52:12 CST 2021
     */
    ConsumedMessageEntity selectByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table consumed_message
     *
     * @mbg.generated Mon Aug 30 19:52:12 CST 2021
     */
    List<ConsumedMessageEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table consumed_message
     *
     * @mbg.generated Mon Aug 30 19:52:12 CST 2021
     */
    int updateByPrimaryKey(ConsumedMessageEntity record);
}