package com.curtisnewbie.module.outbox.dao;

import java.util.List;

import com.alibaba.nacos.shaded.org.checkerframework.common.returnsreceiver.qual.This;
import com.github.pagehelper.PageInfo;
import org.apache.ibatis.annotations.Param;

/**
 * Mapper for message
 *
 * @author yongjie.zhuang
 */
public interface MessageMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table message
     *
     * @mbg.generated Mon Aug 30 19:48:32 CST 2021
     */
    int insert(MessageEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table message
     *
     * @mbg.generated Mon Aug 30 19:48:32 CST 2021
     */
    MessageEntity selectByPrimaryKey(@Param("isPublished") Short isPublished, @Param("messageId") String messageId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table message
     *
     * @mbg.generated Mon Aug 30 19:48:32 CST 2021
     */
    List<MessageEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table message
     *
     * @mbg.generated Mon Aug 30 19:48:32 CST 2021
     */
    int updateByPrimaryKey(MessageEntity record);

    int updateIsPublished(@Param("id") String id, @Param("prev") int prev, @Param("curr") int curr);

    List<MessageEntity> selectUnpublished();
}